version: '3.8'
services:
  medical_clinic:
    container_name: 'medical_clinic_api'
    #    image: 'medical_clinic_stage:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '8090:8080'   #follow you port
#    volumes:
#      - '/home/istad/devops-spring-deployment/api/images:/app/filestorage/images/'